add open shell (sh) and exec cli (cli) commands

diff --git a/bin/dev b/bin/dev
--- a/bin/dev
+++ b/bin/dev
@@ -44,8 +44,8 @@ usage() {
         echo "Actions:"
         echo "  start           Start the development environment (checks and prepares the environment first)"
         echo "  xdebug          Show xdebug status or enable/disable xdebug via http"
-        echo "  cli             execute a cli command (todo)"
-        echo "  sh              start a shell on on a container (todo)"
+        echo "  cli             execute a cli command (use --help for more info)"
+        echo "  sh              start a shell on on a container"
         echo "  build           Build the docker image for the php containers"
         echo "  env             Create missing environment variables"
         echo "  list            Show the list of commands"
@@ -168,7 +168,6 @@ startEnvironment() {
     # start the environment
     set +e
     docker-compose up -d
-    set -e
 
     # show info when errors appear
     if [[ $? -ne "0" ]]; then
@@ -181,10 +180,15 @@ startEnvironment() {
         echo "  By default we are using the network in the range of 10.127.[0-128] for our networks. If "
         echo "  a route for this network already exists this error is shown."
         echo "  SOLUTION: change the network to use in docker-compose.yml"
+        echo "'The Compose file './docker-compose.yml' is invalid'"
+        echo "  Your docker-compose file is corrupted. Maybe your IDE changed something?"
+        echo "  SOLUTION: Restore the original docker-compose.example.yml"
+        exit 1
     else
         echo "The application should now be available at http://$NETWORK_IP"
         echo "Emails will be sent to http://$NETWORK_IP:8025"
     fi
+    set -e
 }
 
 xdebugCmd() {
@@ -213,8 +217,42 @@ xdebugCmd() {
         "disable") xdebugDisable;;
         "enable") xdebugEnable;;
         "status") xdebugStatus;;
-        *) xdebugStatus;;
+        "") xdebugStatus;;
+        "help") usage xdebug;;
+        *) echo "unknown sub command $1" >&2; usage xdebug;;
     esac
+}
+
+execCli() {
+    # start the whole environment if php is not up
+    if ! docker-compose ps php|grep Up > /dev/null; then
+        echo "Local environment is not started, trying to start it..."
+        startEnvironment
+        echo ""
+    fi
+
+    cmd="bin/community"
+    exec docker-compose exec -u $(id -u) php php $cmd "$@"
+}
+
+openShell() {
+    service=${1-php}
+    uid=${2-$(id -u)}
+
+    # start the whole environment if php is not up
+    if ! docker-compose ps php | grep Up > /dev/null; then
+        echo "Local environment is not started, trying to start it..."
+        startEnvironment
+        echo ""
+    fi
+#  set -l script
+
+    if ! docker-compose ps | grep Up >/dev/null | grep $service; then
+        docker-compose exec -u $uid $service sh -c "exec bash -l"
+    else
+        # containers not running after start are for single execution
+        docker-compose run -u $uid --entrypoint sh --rm $service -c "exec bash -l"
+    fi
 }
 
 command=$1 && shift;
@@ -223,6 +261,8 @@ case "$command" in
     "build") buildPhpImage "$@";;
     "start") startEnvironment;;
     "xdebug") xdebugCmd "$@";;
+    "cli") execCli "$@";;
+    "sh") openShell "$@";;
     "list") usage;;
     *) echo "unknown command $command" >&2; usage; exit 1;;
 esac
